on:
  push:
    branches:
      - main
    paths:
      - 'protos/**'
      - '.github/workflows/protos-migration.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  DESTINATION_REPO: "Juanito98/test2"
  ORIGIN_FOLDER: "protos"
  DESTINATION_FOLDER: "generated/protos"

jobs:
  move-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: Juanito98/copybara-action@v0.0.0-alpha.5
        with:
          access_token: ${{ env.GH_TOKEN }}
          destination_repo: ${{ env.DESTINATION_REPO }}
          origin_include: "${{ env.ORIGIN_FOLDER }}/**"
          destination_include: "${{ env.DESTINATION_FOLDER }}/**"
          move: |
            ||${{ env.DESTINATION_FOLDER }}